language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.1
      mono: none
    - os: osx
      osx_image: xcode7.2
      dotnet: 1.0.1
      mono: none

script:
  - dotnet restore
  - dotnet build ./src/BitGo -f .NETStandard,Version=v1.6