language: csharp
solution: BitGo.sln

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview2-003131
      mono: none
    - os: osx
      osx_image: xcode7.2
      dotnet: 1.0.0-preview2-003121
      mono: none

script:
  - dotnet restore
  - dotnet build ./src/BitGo -f .NETStandard,Version=v1.1