version: '0.1.{build}'
configuration:
- Release
platform: Any CPU
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
nuget:
  account_feed: true
  project_feed: true
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
before_build:
- appveyor-retry dotnet restore -v Minimal
build_script:
- dotnet build "src\BitGo" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
after_build:
- dotnet pack "src\BitGo" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
artifacts:
- path: artifacts\**\*.*
deploy:
  - provider: NuGet
    api_key:
      secure: Ov3TAhgoIElQdeOSXWFK081PPha8CGpmUWBABkNbe8AJ06EDa5G3460RwD0Omjbt
    skip_symbols: true
    artifact: /.*\.nupkg/